# Generated by Django 4.0.4 on 2022-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
