# Generated by Django 4.0.4 on 2022-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerside', '0002_queue_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='next_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='people_in_queue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
