# Generated by Django 4.0.4 on 2022-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerside', '0003_shop_next_slot_shop_people_in_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='next_slot',
            field=models.CharField(default='Free Now!', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='people_in_queue',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
